apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: namespace-name
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
#  tls:
#  - hosts:
#      - https-example.foo.com
#    secretName: testsecret-tls
  rules:
  - host: example.foo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 80
