apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-01
  labels:
    vol: pv-01
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs/pv-01
    server: 192.168.234.253
