apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-01
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      vol: pv-01
